# Generated by Django 5.2.5 on 2025-08-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computeruser',
            name='access_level',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Administrator')], default='student', max_length=20, verbose_name='Access Level'),
        ),
        migrations.AlterField(
            model_name='computeruser',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='computeruser',
            name='computer_station',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Computer Station'),
        ),
        migrations.AlterField(
            model_name='computeruser',
            name='contact_number',
            field=models.CharField(max_length=20, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='computeruser',
            name='course',
            field=models.CharField(max_length=100, verbose_name='Course/Program'),
        ),
        migrations.AlterField(
            model_name='computeruser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='computeruser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='computeruser',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='computeruser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login'),
        ),
        migrations.AlterField(
            model_name='computeruser',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='computeruser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='computeruser',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='computeruser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
