# Generated by Django 5.2.5 on 2025-08-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_computerunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComputerUnit',
        ),
    ]
