# Generated by Django 5.2.5 on 2025-08-27 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_delete_computerunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=20, unique=True, verbose_name='Unit ID')),
                ('unit_type', models.CharField(choices=[('desktop', 'Desktop PC'), ('laptop', 'Laptop'), ('workstation', 'Workstation'), ('thin-client', 'Thin Client')], max_length=20, verbose_name='Unit Type')),
                ('processor', models.CharField(max_length=100, verbose_name='Processor')),
                ('ram', models.CharField(max_length=20, verbose_name='RAM')),
                ('storage', models.CharField(max_length=100, verbose_name='Storage')),
                ('operating_system', models.CharField(max_length=50, verbose_name='Operating System')),
                ('location', models.CharField(choices=[('lab-a', 'Lab A'), ('lab-b', 'Lab B'), ('lab-c', 'Lab C'), ('admin-office', 'Admin Office')], max_length=20, verbose_name='Location')),
                ('station_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Station Number')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in-use', 'In Use'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='available', max_length=20, verbose_name='Status')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('performance_score', models.IntegerField(default=100, verbose_name='Performance Score')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Last Maintenance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.computeruser', verbose_name='Assigned User')),
            ],
            options={
                'verbose_name': 'Computer Unit',
                'verbose_name_plural': 'Computer Units',
                'ordering': ['-created_at'],
            },
        ),
    ]
