# Generated by Django 5.2.5 on 2025-08-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_delete_computerunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.CharField(max_length=20, unique=True, verbose_name='Unit ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in-use', 'In Use'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='available', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Computer Unit',
                'verbose_name_plural': 'Computer Units',
                'ordering': ['-created_at'],
            },
        ),
    ]
