# Generated by Django 5.2.5 on 2025-09-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='computeruser',
            name='password',
            field=models.CharField(blank=True, help_text='Password for admin users', max_length=128, null=True, verbose_name='Password'),
        ),
    ]
